name: Mon CI

on:
  push:
    branches: [ main, feature-readme ]

jobs:
  Construction:
    runs-on: ubuntu-latest

    steps:
      - name: RÃ©cupÃ©ration du code
        uses: actions/checkout@v4

      - name: VÃ©rification du contenu
        run: |
          echo "FÃ©licitations ğŸ‰, Pipeline CI dÃ©clenchÃ© avec succÃ¨s !"
          ls -l
